version: '3.4'

services:
  nlp:
    restart: never
    build: .
    environment:
      BRANDON: "brandon"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ./:/app
      - ./.pytorch_transformers:${HOME}/.cache/torch/pytorch_transformers